# Generated by Django 5.2.6 on 2025-10-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_entry_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
