# Generated by Django 5.2.6 on 2025-10-30 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_entry_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='likes',
        ),
        migrations.AddField(
            model_name='entry',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
