# Generated by Django 5.2.6 on 2025-11-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_remotenode_alter_entry_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(editable=False, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='remotenode',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Password they gave us', max_length=100),
        ),
        migrations.AlterField(
            model_name='remotenode',
            name='username',
            field=models.CharField(blank=True, default='', help_text='Username they gave us', max_length=100),
        ),
    ]
