# Generated by Django 5.2.6 on 2025-11-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_merge_20251117_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.CharField(default='text/plain', max_length=50),
        ),
    ]
