# Generated by Django 5.2.6 on 2025-11-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_followrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(editable=False, max_length=500, primary_key=True, serialize=False),
        ),
    ]
